### ISSUE TITLE
How to start playing from the queue?

### ISSUE THREAD

**Issue by keunes** [olejon/spotcommander#103]
So for the MPRIS issue (#100), a workaround is suggested to add stuff to the queue via the overflow menu. Now my question is: if you aren't playing anything yet, how to start doing so from the queue?
(Or am I missing something here?)

I expected a play button in the top right (next to the bin) :)

**Comment by olejon** [comment]
Yeah, a track already must be playing for this to work, because only then the daemon will detect track changes. I button could be added yes, maube in the next version so I will keep this open.

**Comment by olejon** [comment]
Check out issue #100 now. Closing this.
