### ISSUE TITLE
Downgrade for 14.04 (& older)?

### ISSUE THREAD

**Issue by keunes** [olejon/spotcommander#104]
Hello,

Followed the Downgrading instructions, found the heading [If you run Ubuntu 15.04 or newer](https://github.com/olejon/spotcommander/wiki/DowngradeSpotify#if-you-run-ubuntu-1504-or-newer) a little bit confusing. I'm on 14.04, others like me should just ignore that part and continue to the next step. Adding sth like 'lower than 15.04: proceed to next step' as a (sub)title would help.

**Comment by olejon** [comment]
Done.
