### ISSUE TITLE
plays from playlist for 10 seconds then plays the queue

### ISSUE THREAD

**Issue by andydeano** [olejon/spotcommander#110]
using mint 18.1 fully up to date 64bit and Spotify 0.9.17.8  Spotcommander plays from a play list fine. If tracks are then queued, spotcommander will play from the queued tracks, however after the queued track finishes it plays for about 10 seconds from the play list, then realizes and starts to play from the queue again.

**Comment by olejon** [comment]
Hm, that's weird. Can't reproduce it, and first bug of this kind. Are you running any other music player at the same time (not necessarily playing)?

Can you check /usr/share/spotcommander/run/daemon.log and /var/log/apache2/error.log for anything?

Is dbus-monitor running?

ps aux|grep dbus-monitor

BTW which Ubuntu version is your Mint based on?

**Comment by andydeano** [comment]
The version of mint is based on Ubuntu 16.04, no other music players running as far as I'm aware, default install + spotify + spotcommander 



getting this in daemon.log 

Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify
PHP Notice:  fwrite(): send of 4 bytes failed with errno=32 Broken pipe in /usr/share/spotcommander/bin/spotcommander-remote on line 298
PHP Notice:  fwrite(): send of 274 bytes failed with errno=32 Broken pipe in /usr/share/spotcommander/bin/spotcommander-remote on line 298
PHP Notice:  fwrite(): send of 432 bytes failed with errno=32 Broken pipe in /usr/share/spotcommander/bin/spotcommander-remote on line 298
PHP Notice:  fwrite(): send of 432 bytes failed with errno=32 Broken pipe in /usr/share/spotcommander/bin/spotcommander-remote on line 298
PHP Notice:  fwrite(): send of 432 bytes failed with errno=32 Broken pipe in /usr/share/spotcommander/bin/spotcommander-remote on line 298

**Comment by andydeano** [comment]
This is now working as expected. Nothing has changed and the system hasn't even been rebooted. So you can close it down if you want to, thanks.

**Comment by olejon** [comment]
Good. The `mpris` warnings are not important. That's just SpotCommander checking if Spotify is running or not while starting/quitting to update to GUI as fast as possible. It was the `Broken pipe` errors that I didn't really understand and have never seen before. Thanks for updating. Cheers!
