### ISSUE TITLE
Can not authorize with Spotify

### ISSUE THREAD

**Issue by SwooshyCueb** [olejon/spotcommander#111]
**SOLVED:** Everyone, please comment if similar problem occurs.

I'm having pretty much the same issue as #102, though the cause is obviously different, as I have the latest version, which includes the fix for #102.

`run/spotify.token` is empty. Clicking on Browse in the web interface and running `$('div#browse_featured_playlists_div').data('spotifytoken')` in my browsers console just returns an empty string.

**Comment by olejon** [comment]
Hm yeah, I seem to be getting the same. Have to investigate this. Must be some change in Spotify's web API. Sorry!

**Comment by olejon** [comment]
BTW, renewing Spotify tokens seems to work fine (a token expires after 1 hour and SpotCommander then gets a new one using the renewal token). So that's weird. Maybe I'll find a workaround for you before fixing this, as you can get a token from the web API developer console, and just put the data in the file. But give me a couple of days, I've got se health issues. Sorry again.

**Comment by SwooshyCueb** [comment]
No rush! I will shortly be in the process of moving anyway

**Comment by olejon** [comment]
Well I am able to get tokens just fine using code returned from Spotify for the auth request using cURL, but the PHP script that has always worked fails now. Suppose my ISP has done an upgrade, or the Spotify API has broken the feature

> An alternative way of sending the client id and secret is as request parameters (client_id and client_secret) in the POST body, instead of sending them base64-encoded in the header.

Which I use. Using cURL and the id and secret in the header works. Good thing is this can be fixed server side. Hopefully tomorrow.

**Comment by olejon** [comment]
Problem solved now :-)

**Comment by olejon** [comment]
Please comment if any more problems.
