### ISSUE TITLE
Need to run as root

### ISSUE THREAD

**Issue by FiveTwelveMC** [olejon/spotcommander#112]
Hi,

I need to run spotcommander as root. Yes, I know the risks and everything. I cannot run Spotify on non root accounts for a few reasons. Please help.

**Comment by olejon** [comment]
Do you have to run *Spotify* as root or the *spotcommander* daemon? What do you run as root?

**Comment by FiveTwelveMC** [comment]
I need to run the daemon as root. It tells me I can't run as root and to refer to the instructions. Unfortunately, non root isn't an option in my environment.

**Comment by olejon** [comment]
Why isn't it an option? What distribution do you run?

**Comment by FiveTwelveMC** [comment]
I'm running Ubuntu 16.04, however my entire environment is completely configured purely to work on the root user. It's horrible security practice but my entire system revolves around it. I've tried a second user but nothing I can do reasonably will make all of my systems continue to run. So, I need to run this as root. Are there any very major security holes I'd need to account for besides the usual?

**Comment by olejon** [comment]
I assume you installed using the deb package. You can change the code of the daemon to allow it to run as root. How it will work with dbus etc. I do not know.

In the file `/usr/share/spotcommander/bin/spotcommander`, on line 36 the code for not allowing root is. You can remove it so it looks like this from line 36 to 39:

```
	if(empty($display))
	{
		echo "ERROR: You should run this command in your desktop session. Follow the installation instructions carefully.\n\n";
	}
	else
	...
```

**Comment by FiveTwelveMC** [comment]
Perfect, thank you very much

**Comment by olejon** [comment]
So it worked?

**Comment by FiveTwelveMC** [comment]
I'll be testing it as soon as I'm back home. I'll update you.

**Comment by olejon** [comment]
Good

**Comment by FiveTwelveMC** [comment]
Sorry for such a slow response, anyway, I successfully bypassed the root restriction, however I am unable to completely start spot commander as the program looks for the preferences (.config/spotify/prefs) in home/root, when obviously the config is in /root/.config/spotify/prefs. Any idea where I can change where it looks?

**Comment by FiveTwelveMC** [comment]
Ah perfect, I edited functions.php and it works amazingly now! Thank you so much!

**Comment by olejon** [comment]
Goodie. Yeah, just search the source code with `grep` and you'll find where such things are :-)
