### ISSUE TITLE
[FIX RELEASED] All Spotify APIs now suddenly require OAuth

### ISSUE THREAD

**Issue by andydeano** [olejon/spotcommander#113]
**UPDATE FROM DEVELOPER:** See title.

Hi, 

Using Ubuntu 14.04.5 LTS, spotcommander version 13.0-1, spotify desktop client version 0.9.17

apache error log 

[Tue May 30 07:19:08.089611 2017] [mpm_prefork:notice] [pid 1095] AH00169: caught SIGTERM, shutting down
[Tue May 30 07:19:09.024449 2017] [mpm_prefork:notice] [pid 5007] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 07:19:09.024598 2017] [core:notice] [pid 5007] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 07:20:33.594233 2017] [mpm_prefork:notice] [pid 5007] AH00169: caught SIGTERM, shutting down
[Tue May 30 07:20:51.709303 2017] [mpm_prefork:notice] [pid 1141] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 07:20:51.710133 2017] [core:notice] [pid 1141] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 09:18:26.154397 2017] [mpm_prefork:notice] [pid 1141] AH00169: caught SIGTERM, shutting down
[Tue May 30 09:18:27.308594 2017] [mpm_prefork:notice] [pid 28423] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 09:18:27.308739 2017] [core:notice] [pid 28423] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 09:24:11.216578 2017] [mpm_prefork:notice] [pid 28423] AH00169: caught SIGTERM, shutting down
[Tue May 30 09:24:30.560752 2017] [mpm_prefork:notice] [pid 1105] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 09:24:30.569440 2017] [core:notice] [pid 1105] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 09:26:37.134950 2017] [mpm_prefork:notice] [pid 1105] AH00173: SIGHUP received.  Attempting to restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue May 30 09:26:37.227670 2017] [mpm_prefork:notice] [pid 1105] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 09:26:37.227777 2017] [core:notice] [pid 1105] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 09:26:41.162188 2017] [core:warn] [pid 1105] AH00045: child process 4115 still did not exit, sending a SIGTERM
[Tue May 30 09:26:42.163630 2017] [mpm_prefork:notice] [pid 1105] AH00173: SIGHUP received.  Attempting to restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue May 30 09:26:42.243046 2017] [mpm_prefork:notice] [pid 1105] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 09:26:42.243140 2017] [core:notice] [pid 1105] AH00094: Command line: '/usr/sbin/apache2'
[Tue May 30 09:26:51.112946 2017] [mpm_prefork:notice] [pid 1105] AH00169: caught SIGTERM, shutting down
[Tue May 30 09:27:08.633076 2017] [mpm_prefork:notice] [pid 1150] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.21 configured -- resuming normal operations
[Tue May 30 09:27:08.633613 2017] [core:notice] [pid 1150] AH00094: Command line: '/usr/sbin/apache2'

The machine  has had a couple of reboots current time is now 09:39

thanks

**Comment by olejon** [comment]
Nothing unusual in the server log. The ServerName warning is normal by default in a clean install and doesn't matter.

Is this the first time you experience this or did you just install SpotCommander?

Do the other features work?

**Comment by olejon** [comment]
Oh wait, I get the same error. Have to check the API.

**Comment by olejon** [comment]
Ok, so they have added OAuth requirement to all API endpoints. Before this was not necessary. Have to release a new version.

**Comment by andydeano** [comment]
O right, they must have changed that over the weekend then, it was working fine on Friday.

**Comment by olejon** [comment]
Yes, if you see the news on Spotify developer it was made yesterday... I signed up for the newsletter years back but it seems they have stopped it. Couldn't find it now. Such crucial changes should be emailed to all developers in good time before it happenes! Will release a fix soon, unfortunately with no new features then. Have quite a few exciting ones ready with the new beta player API, like full support for v 1.0 on desktop and the ability to control other devices! But it takes time such big changes so must focus on this stupid change now. Suppose too many bots or something flooded their API.

**Comment by olejon** [comment]
Should be fixed in latest release (v 13.1). Please re-open if you have many issues.

**Comment by andydeano** [comment]
can confirm all working now. 
Thanks!

**Comment by olejon** [comment]
Great. Keeping this open for people to see for a while.
