### ISSUE TITLE
Android app not working anymore?

### ISSUE THREAD

**Issue by enzovox** [olejon/spotcommander#120]
Hi,

First of all... thanks, I've been using spotcommander for a long time and it's perfect. 
But I am sorry I have to report that the android app seems not to work anymore after the last update. At least I guess so, everything was working flawlessly but right now I am not able to connect to the daemon from the phone.

I am running spotify and spotcommander on ubuntu 14.04 64 bit (latest update for both), and the android app on Lenovo P2 (android Nougat) 
 
Obviously before opening this issue I have followed the troubleshooting, and everything is correct on ubuntu side: the daemon is working and spotcommander is authorized. But from the phone it's doesn't work, even manually without the app (http://your.computers.ip.address.or.hostname/spotcommander). 

Can you please help me? If you any other info just write me, I am really glad to help.

Thanks, 

Enzo

**Comment by olejon** [comment]
Edited above.

**Comment by enzovox** [comment]
Hi Ole,

- No, I haven't any firewall enabled, I checked in the terminal the ufw status and is inactive
- Yes, on the computer running spotcommander I can go on localhost/spotcommander and it's working
- No, I didn't do any update, not even a minor one, just the normal apps updates on the google play store
- And yes, of course I used the ip address of the pc running spotify :) i copied the yourcomputer.ip.etc just for example 

I really don't know why it stopped working, I haven't changed any configuration compared to last week. Just to be sure I've also removed spotify and reinstall a clean copy of it on the computer, so removing the related config and cache folder, but...nothing, it doesn't work

Other info: I made a try in another computer, and older one, that is running ubuntu 14.04- 32 bit, with an older version of spotify and also of spotcommander (12.8-1) and it works, I can connect through the app

**Comment by olejon** [comment]
Really weird. Can not explain this really.

* On another **computer**, can you access SpotCommander on the primary computer with http://ip.address/spotcommander/ ?

If not, what happens?

**Comment by olejon** [comment]
Edited the above for more details.

**Comment by enzovox** [comment]
Hi Ole,

problem solved. you were right, my Lan/wifi was doing something weird.

At first I couldn't connect even from another computer, so I checked the port with netstat, disable and re-enable apache, reinstall spotcommander, and after that everything was ok. But only with an ethernet connection, not with wifi.

So... even if nothing indicated a problem about it (internet was working fine) I decided as last chance to restart the router. And... I don't know exactly which was the trouble but now everything is working fine also with my phone :)

Sorry if I make you lose some time, but as you can see it was really strange.

Thanks for your help!

ps I know I've left the issue open, but I didn't know if you want to modify the title before closing it

**Comment by olejon** [comment]
No problem. I can always change it later :)
