### ISSUE TITLE
unable to install spotify-client-0.9.17 on Debian 9 x64

### ISSUE THREAD

**Issue by maurerr** [olejon/spotcommander#121]
I had to modify the deb control file for:
from libnspr4-0d to libnspr4
from libnss3-1d to libnss3

you can find the resulted deb here:
https://drive.google.com/file/d/0ByXTrwa38omKeXAzMDVBYnRoUlE/view?usp=sharing

**Comment by olejon** [comment]
Thanks. Will add as alternative packages in the next deb package.
