### ISSUE TITLE
Debian does not install

### ISSUE THREAD

**Issue by BVonk** [olejon/spotcommander#122]
Dear olejon,

I previously had spotcommander installed, but I removed it again.

Now when running the Debian, it does not install when I press the install button. When I press the install button the entry source: unknown disappears and that is that.

Do you know what the issue is? Your help would be greatly appreciated.

**Comment by BVonk** [comment]
I am on Ubuntu 16.04 by the way

**Comment by olejon** [comment]
Try to install GDebi (`apt-get install gdebi`) then in a command line run `sudo gdebi spotcommander-latest.deb` and see what the error could be.

**Comment by BVonk** [comment]
rm: cannot remove '/etc/xdg/autostart/spotcommander.desktop': No such file or directory
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/prerm: line 13: spotcommander: command not found
dpkg: error processing archive spotcommander-latest.deb (--install):
 subprocess new pre-removal script returned error exit status 127
Restoring playlists...
Restoring library...
Restoring authentication configuration...
Setting permissions...
Creating symlink...
Configuring Apache...
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 spotcommander-latest.deb

**Comment by olejon** [comment]
Seems like you have had SpotCommander installed before and it has not been removed correctly. Google how to force uninstall a deb package. Usually there is a cache in /var/xxx , sorry I can't help you more now, I'm sick and in another country. You can also create the files it tries to remove manually, just empty files, like:

/etc/xdg/autostart/spotcommander.desktop
/usr/bin/spotcommander

**Comment by BVonk** [comment]
Alright I will try. Thanks for the help and recover quickly!

**Comment by olejon** [comment]
Thanks. Here are various solutions:

https://askubuntu.com/questions/525088/how-to-delete-broken-packages-in-ubuntu

So first uninstall, when successful, install using gdebi as it shows more information and resolves dependencies as well.

After uninstall and before install it can be a good idea to purge the packages not used anymore, with `sudo apt-get --purge autoremove` . Installation will install them again. Make sure your system is up to date first. The link above should give you the commands (sudo apt-get update && sudo apt-get upgrade)

**Comment by olejon** [comment]
Closing. See issue #121
