### ISSUE TITLE
Request failed. Make sure you are connected. Tap the top right icon to retry.

### ISSUE THREAD

**Issue by timelyfiasco** [olejon/spotcommander#124]
Hi olejon,
I have spotify 0.9. I use Ubuntu 16. I am able to run spotify at boot with the help of your guide in [https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Comma[[https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Commans-to-play-songs-and-playlists-from-terminal/m-p/802971#M87975|n]][[https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Commands-to-play-songs-and-playlists-from-terminal/m-p/802971#M87975|d]][[s-to-play-songs-and-playlists-from-terminal/m-p/802971#M87975]]
](url)

I am content with the current setup. Although, I still want to try the spotcommander. But after installing everything and allowing access from spotify website, I get this error: 

> Request failed. Make sure you are connected. Tap the top right icon to retry. 

Did I miss something?

**Comment by olejon** [comment]
When do you get the error? Immediately after authenticating with Spotify and it goes back to SpotCommander?

**Comment by olejon** [comment]
And in addition to answering the question above, can you post a screenshot?

**Comment by timelyfiasco** [comment]
Yes. After authenticating. Here are the screenshots
![selection_024](https://user-images.githubusercontent.com/33004592/33190813-1d7400e0-d0ec-11e7-93c5-f0adcde90540.png)
![selection_023](https://user-images.githubusercontent.com/33004592/33190815-2010fdda-d0ec-11e7-83ff-e17b41c05049.png)

**Comment by tletum13** [comment]
When do you get the error? Immediately after authenticating with Spotify and it goes back to SpotCommander?

**Comment by olejon** [comment]
I need to do a test to see if there's something wrong with SpotCommander but don't have much time now. Is it the same when you on the computer running Spotify + SpotCommander go to http://localhost/spotcommander/ in a web browser like Chrome or Firefox? If so, copy and paste the URL that is in the address bar when the error occurs.

**Comment by olejon** [comment]
I am not able to reproduce this problem. I just tried on an old Acer Revo 32-bit with the latest Spotify client (1.0.69). **I still ask you to respond to my questions above**. Also:

- Premium or not?
- Any special characters in your Spotify username? Or Facebook user?
- Which version of the Spotify client?
- Any errors in `/var/log/apache2/error.log` when you do auth?

Remember the Spotify desktop client must have been run and you must have logged in in Spotify before starting the SpotCommander daemon. Well the solution to that is just to do it and reboot, but should really not have anything to do with auth.

**Comment by timelyfiasco** [comment]
I tried to reinstall it again today but got the same error. 
`sudo apt-get -y purge spotcommander`
`sudo apt-get install ./spotcommander-latest.deb`
I reboot my desktop. Then I went to localhost/spotcommander. The lock button in the upper right corner redirected me to spotify. I gave permission in Spotify. It redirected me back to spotcommander and I got the same error as above. 
The link is `http://localhost/spotcommander/#profile//spotify_token=eyJhY2Nlc3Nfd0stNmZYbzl3a2ppNXp6clo2dW1Nc1FPUWVNS3RPNlJ6S2UtbXcy...` I cut it because it is very long.
The settings page is showing something
![image](https://user-images.githubusercontent.com/33004592/34288696-b1305452-e729-11e7-8617-65e7dba378b6.png)

> [Fri Dec 22 15:04:41.657704 2017] [:error] [pid 1312] [client 127.0.0.1:60710] PHP Fatal error:  Class 'SQLite3' not found in /usr/share/spotcommander/functions.php on line 2113, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:41.657741 2017] [:error] [pid 1312] [client 127.0.0.1:60710] PHP Stack trace:, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:41.657753 2017] [:error] [pid 1312] [client 127.0.0.1:60710] PHP   1. {main}() /usr/share/spotcommander/nowplaying.php:0, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:41.657762 2017] [:error] [pid 1312] [client 127.0.0.1:60710] PHP   2. saved() /usr/share/spotcommander/nowplaying.php:85, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:41.657769 2017] [:error] [pid 1312] [client 127.0.0.1:60710] PHP   3. sqlite_escape() /usr/share/spotcommander/functions.php:1044, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:45.678619 2017] [:error] [pid 1316] [client 127.0.0.1:60712] PHP Fatal error:  Class 'SQLite3' not found in /usr/share/spotcommander/functions.php on line 2113, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:45.678660 2017] [:error] [pid 1316] [client 127.0.0.1:60712] PHP Stack trace:, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:45.678674 2017] [:error] [pid 1316] [client 127.0.0.1:60712] PHP   1. {main}() /usr/share/spotcommander/nowplaying.php:0, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:45.678682 2017] [:error] [pid 1316] [client 127.0.0.1:60712] PHP   2. saved() /usr/share/spotcommander/nowplaying.php:85, referer: http://localhost/spotcommander/
[Fri Dec 22 15:04:45.678690 2017] [:error] [pid 1316] [client 127.0.0.1:60712] PHP   3. sqlite_escape() /usr/share/spotcommander/functions.php:1044, referer: http://localhost/spotcommander/

**Comment by olejon** [comment]
You seem to lack the necessary dependencies, obviously the basic PHP SQLite package for instance.

You shouldn't install the deb pac that way. First purge it again, then follow the installation instructions: Either double click the deb package and let the GUI Software Center install it (easiest) or if you want to use the command line and get all the dependencies, install `gdebi` and run `sudo gdebi spotcommander-latest.deb` and type `y` when asked to install. Your way won't install the dependencies without an additional command.

So purge again with `sudo apt purge spotcommander` then double click the package on the computer to install it. It should open in the Software Center if you haven't changed any defaults, and wait a few seconds and it'll give you an Install button. It's a click and install process. No need to go command line for the installation. If you prefer it, as said, gdebi makes everything in one command when installing deb packages with dependencies.

Just follow the installation instructions precisely. Couldn't be easier. A few steps. Remember the log out and in again step.

**Comment by timelyfiasco** [comment]
I tried using the software manager but clicking the install button does nothing. 
I tried to install sqlite before purging to see the logs. It shows the following

> [Sat Dec 23 18:44:28.885155 2017] [:error] [pid 1433] [client 127.0.0.1:33426] PHP   1. {main}() /usr/share/spotcommander/nowplaying.php:0, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:28.885162 2017] [:error] [pid 1433] [client 127.0.0.1:33426] PHP   2. saved() /usr/share/spotcommander/nowplaying.php:85, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:28.885165 2017] [:error] [pid 1433] [client 127.0.0.1:33426] PHP   3. get_spotify_token() /usr/share/spotcommander/functions.php:1040, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:28.885168 2017] [:error] [pid 1433] [client 127.0.0.1:33426] PHP   4. get_external_files() /usr/share/spotcommander/functions.php:71, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900493 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP Fatal error:  Call to undefined function curl_multi_init() in /usr/share/spotcommander/functions.php on line 1887, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900524 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900532 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP   1. {main}() /usr/share/spotcommander/nowplaying.php:0, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900538 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP   2. saved() /usr/share/spotcommander/nowplaying.php:85, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900543 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP   3. get_spotify_token() /usr/share/spotcommander/functions.php:1040, referer: http://localhost/spotcommander/
[Sat Dec 23 18:44:32.900548 2017] [:error] [pid 1432] [client 127.0.0.1:33428] PHP   4. get_external_files() /usr/share/spotcommander/functions.php:71, referer: http://localhost/spotcommander/

I ran purge, then 
`sudo dpkg -i spotcommander-latest.deb`
`sudo apt-get install -f`
it didnt add any dependencies
 the errorlog shows

>[Sat Dec 23 18:54:23.374377 2017] [:error] [pid 1341] [client 127.0.0.1:57174] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sat Dec 23 18:54:23.374383 2017] [:error] [pid 1341] [client 127.0.0.1:57174] PHP   1. {main}() /usr/share/spotcommander/main.php:0, referer: http://localhost/spotcommander/
[Sat Dec 23 18:54:23.374386 2017] [:error] [pid 1341] [client 127.0.0.1:57174] PHP   2. check_for_updates() /usr/share/spotcommander/main.php:240, referer: http://localhost/spotcommander/
[Sat Dec 23 18:54:23.374388 2017] [:error] [pid 1341] [client 127.0.0.1:57174] PHP   3. get_external_files() /usr/share/spotcommander/functions.php:2033, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101153 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP Fatal error:  Call to undefined function curl_multi_init() in /usr/share/spotcommander/functions.php on line 1887, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101165 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101170 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP   1. {main}() /usr/share/spotcommander/profile.php:0, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101177 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP   2. save_spotify_token() /usr/share/spotcommander/profile.php:34, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101179 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP   3. get_profile() /usr/share/spotcommander/functions.php:130, referer: http://localhost/spotcommander/
[Sat Dec 23 18:55:16.101181 2017] [:error] [pid 1343] [client 127.0.0.1:57264] PHP   4. get_external_files() /usr/share/spotcommander/functions.php:1769, referer: http://localhost/spotcommander/

Lastly, I tried gdebi. It also didnt add any dependencies. The error log below:
`sudo gdebi spotcommander-latest.deb`
>[Sat Dec 23 19:00:53.904528 2017] [:error] [pid 3832] [client 127.0.0.1:57442] PHP   2. get_external_files() /usr/share/spotcommander/error.php:59, referer: http://localhost/spotcommander/
[Sat Dec 23 19:01:05.017584 2017] [mpm_prefork:notice] [pid 1316] AH00169: caught SIGTERM, shutting down
[Sat Dec 23 19:01:40.389443 2017] [mpm_prefork:notice] [pid 1299] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Sat Dec 23 19:01:40.389707 2017] [core:notice] [pid 1299] AH00094: Command line: '/usr/sbin/apache2'
[Sat Dec 23 19:03:06.230250 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP Fatal error:  Call to undefined function curl_multi_init() in /usr/share/spotcommander/functions.php on line 1887, referer: http://localhost/spotcommander/
[Sat Dec 23 19:03:06.230281 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sat Dec 23 19:03:06.230286 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP   1. {main}() /usr/share/spotcommander/profile.php:0, referer: http://localhost/spotcommander/
[Sat Dec 23 19:03:06.230289 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP   2. save_spotify_token() /usr/share/spotcommander/profile.php:34, referer: http://localhost/spotcommander/
[Sat Dec 23 19:03:06.230295 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP   3. get_profile() /usr/share/spotcommander/functions.php:130, referer: http://localhost/spotcommander/
[Sat Dec 23 19:03:06.230298 2017] [:error] [pid 1311] [client 127.0.0.1:34430] PHP   4. get_external_files() /usr/share/spotcommander/functions.php:1769, referer: http://localhost/spotcommander/

Btw, I changed the www/html if it matters.

**Comment by olejon** [comment]
It should open in "Software Install" (GNOME program that replaced the Ubuntu Software Center) and it might take some time for it to install, depending on your PC and Internet connection. It's quite slow to install packages manually just like the old Ubuntu Software Center was.

**I strongly recommend you anyway, to be able to see any APT errors, to install gdebi, with:**

`sudo apt install gdebi`

`sudo apt purge spotcommander`

Then `sudo gdebi spotcommander-latest.deb`

Paste output if any errors. `dpkg -i` you can only use if all dependencies are already installed. If you're unlucky you can mess up APT and get into a dependency hell using your ways.

When you install SpotCommander it adds my SpotCommander repository so it's updated with the system an no user action required when a new version is out. If you know how to add repositories, add `http://repository.olejon.net/deb/` to APT sources, add the key you'll find on that URL and run `sudo apt update` and `sudo apt install spotcommander`.

**Comment by timelyfiasco** [comment]
Hi olejon, that was what I did the last time. 
`sudo apt purge spotcommander`
`sudo gdebi spotcommander-latest.deb`
It didnt work last time but now it partially works. I can click next, play ,previous. The playlist, library shows nothing. Browse doesnt work also. The output is in the image below. 

The output in gdebi is the same 
>Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

>Remote control for Spotify
 SpotCommander is a remote control for Spotify for Linux, 
 optimized for mobile devices. 
 It works on any device with a modern browser, 
 and it's free and open source.
Do you want to install the software package? [y/N]:Y
Selecting previously unselected package spotcommander.
(Reading database ... 351225 files and directories currently installed.)
Preparing to unpack spotcommander-latest.deb ...
Unpacking spotcommander (13.4-1) ...
Setting up spotcommander (13.4-1) ...
Restoring playlists...
Restoring library...
Restoring authentication configuration...
Setting permissions...
Creating symlink...
Configuring Apache...
Adding repository...
Adding daemon to startup applications...

	 ---------------------------------------------------------------------------
	 | Installation complete!                                                  |
	 |                                                                         |
	 | You must now start the daemon. See the wiki for instructions.           |
	 |                                                                         |
	 | You should then be able to control Spotify by going to:                 |
	 |                                                                         |
	 | http://this.computers.ip.address.or.hostname/spotcommander              |
	 ---------------------------------------------------------------------------

![pasted_image](https://user-images.githubusercontent.com/33004592/34323332-c371928c-e87f-11e7-8f52-89f6d3e7a26f.png)

The errorlog in apache remains the same. 
>[Sun Dec 24 07:46:24.091333 2017] [:error] [pid 1327] [client 127.0.0.1:57094] PHP   2. get_external_files() /usr/share/spotcommander/recently-played.php:28, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:25.467392 2017] [:error] [pid 1330] [client 127.0.0.1:57108] PHP Fatal error:  Call to undefined function curl_multi_init() in /usr/share/spotcommander/functions.php on line 1887, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:25.467425 2017] [:error] [pid 1330] [client 127.0.0.1:57108] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:25.467434 2017] [:error] [pid 1330] [client 127.0.0.1:57108] PHP   1. {main}() /usr/share/spotcommander/recently-played.php:0, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:25.467441 2017] [:error] [pid 1330] [client 127.0.0.1:57108] PHP   2. get_external_files() /usr/share/spotcommander/recently-played.php:28, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:34.970451 2017] [:error] [pid 1331] [client 127.0.0.1:57120] PHP Fatal error:  Call to undefined function curl_multi_init() in /usr/share/spotcommander/functions.php on line 1887, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:34.970504 2017] [:error] [pid 1331] [client 127.0.0.1:57120] PHP Stack trace:, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:34.970521 2017] [:error] [pid 1331] [client 127.0.0.1:57120] PHP   1. {main}() /usr/share/spotcommander/playlists.php:0, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:34.970536 2017] [:error] [pid 1331] [client 127.0.0.1:57120] PHP   2. refresh_spotify_playlists() /usr/share/spotcommander/playlists.php:33, referer: http://localhost/spotcommander/
[Sun Dec 24 07:46:34.970549 2017] [:error] [pid 1331] [client 127.0.0.1:57120] PHP   3. get_external_files() /usr/share/spotcommander/functions.php:665, referer: http://localhost/spotcommander/

**Comment by olejon** [comment]
Now you obviously lack php-curl... I have tested this package even on a clean Ubuntu 17.10 in a VM that got pulled recently. Don't know what's special about your configuration, maybe some software installed from another program that does not use the standard packages. I have no idea really.

Well let's just install all the dependencies manually, and it should work. Some of them are probably installed already but they just won't be installed then, but some you lack.

So just run:

`sudo apt install apache2 apache2-utils inotify-tools libapache2-mod-php php-cli php-curl php-json php-sqlite3 qdbus xautomation`

**Reboot**

(Tip: All deps from a deb package can be seen by using for example the GDebi GUI or extract the deb package, then the control.tar.gz package and open the control file).

**Comment by olejon** [comment]
(Edited somewhat to what should be the ultimate solution above...)

**Comment by timelyfiasco** [comment]
Hi, I did another installing all the required dependencies above. Then I removed and installed spotcommander but nothing changed. I can used spotcommander only to play and pause music. 
Thank you for the help Olejon. I will try this next time on a clean os.
