### ISSUE TITLE
Works fine using webbrowser on machine that has spotify on, but not on other machine on LAN

### ISSUE THREAD

**Issue by anfractuosity** [olejon/spotcommander#126]
Hi,

Spotcommander, seems to work fine for me in the webbrowser on the machine that runs spotify, but for some reason although the interface displays fine from my remote PC, it doesn't seem to let me play or click on any buttons, I expect I could be missing something obvious, but I'm not sure what.

Cheers
Chris

**Comment by olejon** [comment]
Does it have touch screen support?

**Comment by anfractuosity** [comment]
Yes! Wow, it works with touchscreen.  

Is there any way I can get it to work just by clicking?  I don't tend to use the touchscreen feature, as this is on my laptop.

**Comment by olejon** [comment]
Do you never use the touch screen in the browser?

If you use Chrome or Chromium there are 3 options:

1. Disable touch
2. Modify SpotCommander's code to force mouse and keyboard only (doesn't support both)
3. Make a launcher shortcut that opens SpotCommander as a "Chrome App" with touch disabled

If you don't use Chrome or Chromium I suggest you use it for SpotCommander only and check out the wiki page for how to run SpotCommander as a standalone app and I'll help you disable touch.

Let me know.

Or use touch if convenient.

**Comment by anfractuosity** [comment]
Thanks a lot for the pointers. I created the standalone app like you said and disabled touch.  It works really smoothly now!

The interface of spotcommander is very nice by the way, keep up the good work 👍 

I'll close this issue now.

**Comment by olejon** [comment]
Great :)
