### ISSUE TITLE
Everything done but doesn't work

### ISSUE THREAD

**Issue by wallneb** [olejon/spotcommander#129]
Dear!

I've downloaded SpotCommander and the spotify client like u mentioned in the description.
After all i tried to connect through SpotCommander to Spotify.
My client was restartet and logged out and re-logged in before starting manually the daemon on SpotCommander because it wasn't started automatically.

Then the page told me to login through the Spotify site inself with the same account i'm using at the OPENED spotify client.
I did this. Then it said "Success! Reload everything using the button in the top right corner.
After this I always get an Error but when i press the "Play"-Logo at the bottom of SpotCommander, my Spotify client begins play music. But anything else doesn't work.

Need help please!

**Comment by olejon** [comment]
I need some more information:

1) Which distribution and version are you running?
2) Did you install Spotify as [described here](https://github.com/olejon/spotcommander/issues/128)

**Comment by wallneb** [comment]
I already removed SpotCommander cause i don't really need.
Thanks for your help!
