### ISSUE TITLE
unable to search for local files

### ISSUE THREAD

**Issue by Henrytje** [olejon/spotcommander#135]
Using spotify 0.9 and ubuntu 18, I am able to play local files when accessing spotify itself. However, using spotcommander, I don't see the option to browse my local files.

Do I have to configure this myself in the config file of spotcommander?

**Comment by olejon** [comment]
It is unfortunately impossible to get your Local Files from anywhere, not through D-Bus, and certainly not from Spotify's API. If you make a Playlist with all of them in it on your PC, it should work if using v Spotify 0.9.17, but not on the newer v 1.0 versions I believe, as it (stupid devs when building new version) simply didn't make sure `spotify:local` URIs works on it. At least I guess, without remembering or having tried now.
