### ISSUE TITLE
Spotify playlist won't sync

### ISSUE THREAD

**Issue by olejon** [olejon/spotcommander#16]
_From [Leo.Hube...@gmail.com](https://code.google.com/u/110042099989999927553/) on January 27, 2013 16:02:32_

What steps will reproduce the problem? 1.Linux mint, Last official Spotify release (in repo, 0.8.8.323)
2. HTC one 
3.No playlist appears when I connect. Even after I restart Spotify What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Cf 1 Please provide any additional information below.

_Original issue: http://code.google.com/p/spotcommander/issues/detail?id=22_

**Comment by Hoaas** [comment]
Also have this issue, norwegian account without Facebook signup. Facebook was linked at some point, but not anymore. Have a playlist.bnk file on my windows install.

Also tried mopidy and a spotify plugin for Kodi, they both seem to have a playlist.bnk file. (but they might be using the same library or something?) Tried copying these files over, but didn't seem to have any effect.

**Comment by olejon** [comment]
First of all, in the newest version, there is no reading of .bnk files. In the newest version you must log in and your playlists are fetched autmatically. Note that playlists marked as collaborative will NOT be fetched. You can temporarily import them as not-collaborative or import them manually.

See the wiki for more information: https://github.com/olejon/spotcommander/wiki/Use#playlists

**Comment by Hoaas** [comment]
I'm not seeing any automatic fetching.
I can only see the Starred playlist, which is also the only one I have shared.

When I click "Import from Spotify" > "Continue" I get "Could not import playlists".

Library is filled just fine though.
(manual imports work fine)

**Comment by olejon** [comment]
I just tried in a clean and updated Ubuntu 14.10 64-bit virtual machine and it worked as it should.

Some questions:

1. Have you tried to deauthorize and authorize again?
2. Which distro are you running?
3. What is your Spotify username? (contains any special characters?)
4. Do you get any errors in `/var/log/apache2/error.log`? (this is the location on Ubuntu)

**Comment by Hoaas** [comment]
1. Yes
2. Arch Linux
3. Hoås .. so one. Folder on disk is encoded as ho%c3%a5s-user
4. Running in nginx. Can't see any errors in nginx or php logs related to spotcommander.

**Comment by olejon** [comment]
Didn't know they allowed Scandinavian letters. Well, have to do some testing, but I don't have time right now. Hopefully soon. In the meantime, import your most used playlists manually.

**Comment by olejon** [comment]
Check if it works in Spotify's developer console:

https://developer.spotify.com/web-api/console/get-playlists/

You must first click the "Get OAuth token" button, and allow everything.

**Comment by Hoaas** [comment]
Spotify actually allows unicode, and have had some issues with it: 
https://labs.spotify.com/2013/06/18/creative-usernames/

API works fine there. Think I found the error though.
Spotify's web api creates the URL https://api.spotify.com/v1/users/ho%C3%A5s/playlists

I threw in an error_log($api_uri); in  function import_spotify_playlists(), and got this out:
https://api.spotify.com/v1/users/hoås/playlists?limit=50

So appears to be an encoding issue.
I've fixed it locally here now, I'll send a pull request.

**Comment by olejon** [comment]
Thanks. Have had problems with special characters before, but not with actual users of SpotCommander (maybe you're the first? :-), but for example browsing a playlist belonging to a user with a special character in its username, which should work, cover art etc. all depends on the URL formatting.

Will fix this when in the next version, but won't rush it since there doesn't seem to be a widespread problem. Have other projects ongoing.

**Comment by olejon** [comment]
Fixed in v 12.4.
