### ISSUE TITLE
No access to spotcommander

### ISSUE THREAD

**Issue by jonnius** [olejon/spotcommander#80]
Even though the daemon is running nothing is find trying to open http://localhost/spotcommander on the same computer and the Android App is not able to connect, too. 
Running 'spotcommander start' just answers 'Starting daemon...' and I can see the daemon running in system monitor...

**Comment by olejon** [comment]
Could you elloborate a little more?

1. Which distro are you running?
2. What error do you see then you go to `http://localhost/spotcommander/`?

**Comment by jonnius** [comment]
Sorry for not providing more information.
1. I am running Fairphone OS which is Android 4.2.
2a. the error in firefox:

Unable to connect

Firefox can't establish a connection to the server at localhost.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

2b. the error in SpotCommander Android App:
SpotCommander: Something went  wrong.
Make sure that you are connected and that the URL is correct.

**Comment by olejon** [comment]
You didn't mention what Linux distro you are running. Forget about the phone, it doesn't matter as long as you can't reach it from localhost.

**Comment by jonnius** [comment]
It's Ubuntu Gnome 14.10.

**Comment by olejon** [comment]
Can you verify that Apache is running on the PC by running this command:

`ps aux | grep apache`

?

**Comment by jonnius** [comment]
It is not running.

**Comment by olejon** [comment]
Great :-) What was the problem?

**Comment by jonnius** [comment]
After removing owncloud from the machine a owncloud-apache start script was still there that caused apache not start. After removing this, apache works again.

**Comment by olejon** [comment]
I see. Thanks for the explanation.
