### ISSUE TITLE
Unable to use Spotcommander from Chrome or Firefox on Windows.

### ISSUE THREAD

**Issue by mwiley** [olejon/spotcommander#81]
On Windows 8.1, Spotcommander is unresponsive on Chrome and Firefox. Nothing I click on will do anything. It does work in Internet Explorer, Firefox on Linux Mint (on the device I'm trying to control), and Android. I'd like to give some more information, but I checked the Developer console on Chrome, and there are no errors. I already tried clearing the cache.

**Comment by olejon** [comment]
This PC with Windows 8.1, does it support touch?

**Comment by mwiley** [comment]
Yes. So I can use it with the touchscreen, but I don't see any option to enable the mouse, and that means I can't use it on my external monitor at all.

**Comment by olejon** [comment]
1. In Chrome, open the URL `chrome://flags/#touch-events`
2. In the list, choose Disable

Handling both touch events and mouse events is tricky stuff so I haven't made hybrid devices a priority. The current touch events implementation is not ideal. It was made by the WebKit (Apple) team up when hybrid devices was not in anyone's minds. Finally Google has decided to support Microsoft's pointer events, but that'll take time, and won't work on pre-Lollipop devices that don't get updates to their WebViews.

**Comment by mwiley** [comment]
Awesome. Thanks.
