### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by davidb2002** [olejon/spotcommander#85]
Firstly, i've had a look at the source code. Wow! this is pretty good stuff. Possibly the best open source controller for Spotify.

I've been looking for something similar to run on a WAMP server can thought I'd see how this gets. Obviously, it didn't work because it calls alot of linux based commands and looks for the daemon.

From what I can tell, the majority of the code is portable to windows. It's only the interaction with the daemon which needs work for it to work with Windows.

I imagine i'm not the first to ask this. Is there any plans to port this for WAMP servers? I'd have a go myself, but the whole 'daemon' thing has me lost (i'm a PHP web developer).

Cheers!
David

**Comment by olejon** [comment]
Hi. I've had a lot of requests about this. I know there are Windows controllers out there, but I have no idea how they work, but my guess is their pretty hacky (beyond my programming skills), as they tend to be unreliable.

Linux is much easier because Spotify supports the basics through D-Bus so simple command line commands can be used. As it appears so does OS X so there is an effort by another user to get it working fully (a lot works already). As I've said before, any help is wanted. The code is there.

**Comment by davidb2002** [comment]
I imagine there is a Windows alternative for practically every linux command out there.

https://www.google.co.uk/search?q=dbus+for+windows&oq=dbus+for+windows&aqs=chrome..69i57j0l5.2225j0j7&sourceid=chrome&es_sm=122&ie=UTF-8

It's just taking the time to research and implement. Then the final stage would be to write instructions or an easy script to install of these additional requirements in a package. This seems to be the main linux commands:

pgrep
pkill
dbus-minotor
inotifywait
php (requires wamp innstall)
command
pacmd
unix://

I've got some linux skills, but I use a wamp setup at home. It might be something i'm willing to look into.

**Comment by olejon** [comment]
Yes, but does Spotify on Windows expose a D-Bus interface? My guess is not. Current version for Windows and OS X is 1.0. They haven't even implemented D-Bus support in the Spotify 1.0 Linux Beta yet.

**Comment by davidb2002** [comment]
hm...all this is starting to sound like voodoo that i'm probably not going to be able to figure out.

Perhaps a better approach would to build one from scratch using the Spotify PHP api and try to replicate the spotify web player.

**Comment by olejon** [comment]
It would be possible to make a Chrome extension and use SpotCommander to control the web player, I think. You only need to know web development.

Anyway, it may seem like an OS X version may be available some time in the future. On OS X it seems like it is similarily easy to control Spotify using `osascript`, just like D-Bus on Linux. AFAIK there is no such thing on Windows for Spotify so you can't simply use PHP's exec() function, which is what SpotCommander does.
