### ISSUE TITLE
'Can not connect to the daemon' raspberry

### ISSUE THREAD

**Issue by Skyrid3r** [olejon/spotcommander#88]
For some reason, I am unable to make this work on my raspberry on the local network. (using debian - Rasbarian) According to:

ps aux | grep spotcommander

pi        2869  0.0  0.2   4284  2316 pts/0    S    13:17   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-inotifywait /usr/share/spotcommander
pi        2871  0.0  0.2   4284  2416 pts/0    S    13:17   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-queue /usr/share/spotcommander qdbus
pi        2873  0.0  0.1   4316  1512 pts/0    S    13:17   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-queue /usr/share/spotcommander qdbus
pi        2874  0.0  0.0   1840   376 pts/0    S    13:17   0:00 inotifywait -e modify /usr/share/spotcommander/run/daemon.inotify
pi        2906  0.0  0.1   3552  1756 pts/0    S+   13:24   0:00 grep --color=auto spotcommander

It appears to be running, just fine. I even launched it from a remote desktop. Restarted the pi and re-ran the command through the remote, but I keep getting the error..

Any specific reason why?

**Comment by olejon** [comment]
As the official Spotify client does not work on ARM (Raspberry Pi), there is no use for SpotCommander. You can try mopidy + one of the available clients instead.
