### ISSUE TITLE
My phone can't find my computer.

### ISSUE THREAD

**Issue by orando77** [olejon/spotcommander#89]
I installed spotcommander on both my computer, running elementary OS Luna (built on Ubuntu 12.04), and on my phone, running Android 4.4.4. I've checked the daemon, and it seems to be working fine: I've followed the instructions and when executing the command "ps aux | grep spotcommander" it does return a bunch of processes (I have no idea how to interpret them though).
Any help will be greatly appreciated.

**Comment by olejon** [comment]
What's the LAN IP address of your computer?

http://www.howtogeek.com/howto/17012/how-to-find-your-ip-address-in-ubuntu/

**Comment by olejon** [comment]
Closed due to lack of response.
