### ISSUE TITLE
Hide playlists with no edit rights

### ISSUE THREAD

**Issue by keunes** [olejon/spotcommander#92]
When trying to add a number to a playlist that you don't own (or when it's a collaborative list, I assume) via Menu -> More -> Add to playlist, a snackbar is presented in Antdroid saying "No access to playlist".

I have lists of my own that have roughly the same name of lists that I follow (e.g. Chill and Chill out). Given that a regular snackbar doesn't attract much attention, it would be nice if those lists could simply (simply as in from a UX experience) be filtered out of the 'add to...' menu.

**Comment by olejon** [comment]
That's a good idea, or maybe mark them as unavailable. I'll keep this open to remember it.

**Comment by olejon** [comment]
Fixed in v 12.5.

**Comment by keunes** [comment]
Cool :)
