### ISSUE TITLE
Opensuse Leap -  spotcommander blank page in the Android app when opening the Computer.

### ISSUE THREAD

**Issue by ezio84** [olejon/spotcommander#96]
Hi dude!
I installed the app on the new Opensuse Leap, following Opensuse 13.2 instructions (PS: there's no libtqt4 but libqt4), then when running "http://your.computers.ip.address.or.hostname/spotcommander" in the browser it gave me an Access Denied 403 error by Apache.
In the /var/log/apache2 /error_log i had:

[Fri Nov 06 11:06:35.567903 2015] [autoindex:error] [pid 1271] [client 192.168.0.4:35501] AH01276: Cannot serve directory /srv/www/htdocs/spotcommander/: No matching DirectoryIndex (index.html,index.html.var) found, and server-generated directory index forbidden by Options directive

In the Android app, same 403 error.

So i fixed it adding "index.php" in the /etc/apache2/httpd.conf file:

List of resources to look for when the client requests a directory
DirectoryIndex index.html index.html.var index.php

Now, the 403 error is gone, but running "http://your.computers.ip.address.or.hostname/spotcommander"  in the browser just let me save a "download" file, while in the Android app i have a blank screen when opening the Computer.
Here's the "download" file content:
http://pastebin.com/wkBpMAZd

Bye and thanks as usual for the great app!

**Comment by olejon** [comment]
Hi. Thanks, I have updated the wiki to `libqt4`.

Now downloading Leap and will install it in VirtualBox to see what happens. My guess is some PHP package/module not being installed automatically when resolving dependencies to the packages you are instructed to install in the wiki. Note that the wiki page says:

"This guide was written for openSUSE 13.2. I can not guarantee that it will work on other openSUSE versions."

**Comment by ezio84** [comment]
Thanks!

**Comment by olejon** [comment]
I have found the correct way to do this.

php5 is not enabled as a module in apache2 by default. Running `a2enmod php5` fixes the problem and SpotCommander opens as expected. I will add it to the wiki.

I also noticed that the package `libqt4-x11` was not installed as a dependency, like in openSUSE 13.2, and then Spotify stable will not run. I have added it to the guide to install Spotify stable.

Don't know if it matters, but during installation I chose "Add online repositories during installation", or something like that, and chose this:

http://i.imgur.com/JPlefNT.png

**Comment by olejon** [comment]
I have now updated the [installation guide for installing Spotify stable](https://gist.github.com/olejon/c444ac99d7b6625e458f) and updated the [SpotCommander installation instructions for openSUSE 13.2 and openSUSE Leap](https://github.com/olejon/spotcommander/wiki/InstallOnOpenSUSE) so that it should work out-of-the-box.

**Comment by ezio84** [comment]
Confirmed, a2enmod php5 did the trick! Thanks again.

**Comment by olejon** [comment]
Great :-)
