### ISSUE TITLE
"No music playing" (Kubuntu 15.10 - Plasma 5.5)

### ISSUE THREAD

**Issue by nicofrand** [olejon/spotcommander#97]
Hi, 

I am using Kubuntu 15.10 with plasma 5.5.
Spotcommander is running : 

```console
nicofrand@desktop:~$ ps aux | grep spotcommander
nicofra+  2126  0.0  0.2 255584 25572 ?        S    12:18   0:00 php /usr/share/spotcommander/bin/spotcommander-remote
nicofra+  2128  0.0  0.0  12500  2740 ?        S    12:18   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-inotifywait /usr/share/spotcommander
nicofra+  2130  0.0  0.0   6528   768 ?        S    12:18   0:00 inotifywait -e modify /usr/share/spotcommander/run/daemon.inotify
nicofra+  2131  0.0  0.0  12504  2796 ?        S    12:18   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-queue /usr/share/spotcommander /usr/lib/x86_64-linux-gnu/qt4/bin/qdbus
nicofra+  2133  0.0  0.0  12568  2528 ?        S    12:18   0:00 /bin/bash /usr/share/spotcommander/bin/spotcommander-queue /usr/share/spotcommander /usr/lib/x86_64-linux-gnu/qt4/bin/qdbus
nicofra+  2486  0.0  0.0   9556  2192 pts/1    S+   12:22   0:00 grep --color=auto spotcommander
```

And I am connected from my phone to my computer. 
However I cannot control anything, the message "No music playing" remains… I tried with http://localhost/spotcommander but the issue is still there. It fetched my playlists and library though.

I checked the [Troublshooting guide](https://github.com/olejon/spotcommander/wiki/Troubleshooting#now-playing-always-says-no-music-is-playing) but everything seems fine for me:

```bash
nicofrand@desktop:~$ cat .config/spotify/Users/nicofrand-user/prefs 
ui.seen.tray_icon=true
ui.local_playlists_imported=true
ui.sidebar_seen_at_fallback=1426249953
ui.repeat=1
ps.license-agreements="0.8.8-FR,1.0.0-FR"
ui.last_seen_product_type="basic-desktop"
```

```console
nicofrand@desktop:~$ ps aux | grep spotify
nicofra+  2000  7.4  1.1 1018796 144104 ?      Sl   12:18   0:30 /usr/bin/spotify
nicofra+  2025  0.0  0.1 443788 24064 ?        S    12:18   0:00 /usr/bin/spotify
nicofra+  2026  0.0  0.2 331128 34760 ?        S    12:18   0:00 /opt/spotify/spotify-client/Data/SpotifyHelper --type=zygote --no-sandbox --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data
nicofra+  2080 27.6  1.1 1065308 146916 ?      Sl   12:18   1:53 /opt/spotify/spotify-client/Data/SpotifyHelper --type=renderer --js-flags=--harmony-proxies --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data --product-version=Spotify/0.9.17.1.g9b85d436 --disable-accelerated-2d-canvas --disable-accelerated-video-decode --channel=2000.1.477401709
nicofra+  2082  0.1  0.4 940324 55628 ?        Sl   12:18   0:00 /opt/spotify/spotify-client/Data/SpotifyHelper --type=renderer --js-flags=--harmony-proxies --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data --product-version=Spotify/0.9.17.1.g9b85d436 --disable-accelerated-2d-canvas --disable-accelerated-video-decode --channel=2000.2.2007606162
nicofra+  2083  0.1  0.4 941428 56188 ?        Sl   12:18   0:00 /opt/spotify/spotify-client/Data/SpotifyHelper --type=renderer --js-flags=--harmony-proxies --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data --product-version=Spotify/0.9.17.1.g9b85d436 --disable-accelerated-2d-canvas --disable-accelerated-video-decode --channel=2000.3.1883204589
nicofra+  2090  0.1  0.4 937136 56580 ?        Sl   12:18   0:00 /opt/spotify/spotify-client/Data/SpotifyHelper --type=renderer --js-flags=--harmony-proxies --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data --product-version=Spotify/0.9.17.1.g9b85d436 --disable-accelerated-2d-canvas --disable-accelerated-video-decode --channel=2000.4.1160866538
nicofra+  2153 30.8  1.0 489812 130876 ?       Sl   12:18   2:06 /opt/spotify/spotify-client/Data/SpotifyHelper --type=gpu-process --channel=2000.5.1375721167 --no-sandbox --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data --supports-dual-gpus=false --gpu-driver-bug-workarounds=0,19,22 --gpu-vendor-id=0x10de --gpu-device-id=0x0fc1 --gpu-driver-vendor=NVIDIA --gpu-driver-version=352.63 --lang=en-US --locales-dir-path=/opt/spotify/spotify-client/Data/locales --log-severity=disable --resources-dir-path=/opt/spotify/spotify-client/Data
nicofra+  2735  0.0  0.0   9556  2124 pts/1    R+   12:25   0:00 grep --color=auto spotify
```

I do not know what might be the issue nor where to search, could anyone help me please ?

**Comment by olejon** [comment]
Which version of Spotify are you running?

**Comment by nicofrand** [comment]
0.9.17.1.g9b85d436 (the latest one from the repo).

**Comment by olejon** [comment]
When playing a track, what do you get when you run this command in a terminal (as the desktop user running Spotify):

`qdbus org.mpris.MediaPlayer2.spotify / org.freedesktop.MediaPlayer2.GetMetadata`

**Comment by nicofrand** [comment]
Service 'org.mpris.MediaPlayer2.spotify' does not exist.

**Comment by nicofrand** [comment]
Reinstalling spotify after a apt-get purge actually solved the issue !

**Comment by olejon** [comment]
Weird, but good :-)

**Comment by nicofrand** [comment]
It actually came back. I suspect KDE with plasma 5.5…

**Comment by olejon** [comment]
Hm, have you turned off notifications for Spotify? Because then SpotCommander can not retrieve metadata for the currently playing track.

When a track is playing, what do you get if you run this command in a terminal (as the desktop user running Spotify):

`qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player PlaybackStatus`

**Comment by nicofrand** [comment]
> Cannot find 'org.freedesktop.DBus.Properties.Get' in object /org/mpris/MediaPlayer2 at org.mpris.MediaPlayer2.spotify

Just to be sure I tried to use qdbus with VLC (`qdbus org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause`) and that worked.

**Comment by olejon** [comment]
When Spotify is playing, what do you get when you run:

`qdbus | grep -i spotify`

**Comment by nicofrand** [comment]
com.spotify.qt

**Comment by olejon** [comment]
Seems like Spotify isn't registering MPRIS in DBus. Maybe because of KDE, although I haven't had this issue reported before.

Anyway, you can fix this by modifying the code, replacing all instances of `org.mpris.MediaPlayer2.spotify` with `com.spotify.qt` in the necessary files, right after `$qdbus` or `$QDBUS` in `bin/spotcommander-queue ` (BASH script). If you installed the deb package the files are in `/usr/share/spotcommander`

There are 4 files that must be modified. [You can see which here](https://github.com/olejon/spotcommander/search?utf8=%E2%9C%93&q=org.mpris.MediaPlayer2.spotify).

After that, restart the daemon, or simply reboot. Leaving this open for others to see.

**Comment by nicofrand** [comment]
Thanks ! I'll wait for an update of Plasma 5.5 to see if that solves anything before modifying the code :) !

**Comment by olejon** [comment]
Closed due to inactivity. Reopen if necessary.
