### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by makovz** [olejon/spotcommander#98]
Hello,

After trying many workarounds I got stuck. I get the message "net::ERR_connection_refused" from the server if I add the connection manually, and if I try to scan my LAN the computer running spotcommander isn't even detected!! The daemon seems running properly.

Please help me!
Thanks a lot
Marco

**Comment by olejon** [comment]
But does it work if you open a web browser **on the computer running Spotify & SpotCommander** and go to `http://127.0.0.1/spotcommander/` ?

**Comment by makovz** [comment]
No, it doesn't work.

**Comment by makovz** [comment]
any suggestions? thanks!

**Comment by olejon** [comment]
What distribution and version are you running?

**Comment by makovz** [comment]
last update of ubuntu 14.04

**Comment by olejon** [comment]
Looks like the web server isn't running then, for some reason. It should be installed and started at boot if you installed SpotCommander normally.

What happens if you run this command?

`sudo service apache2 start`

?

**Comment by makovz** [comment]
this is the output:

 * Starting web server apache2                                                                                                            * 
 * The apache2 configtest failed.
Output of config test was:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for main error log
(2)No such file or directory: AH02291: Cannot access directory '/var/log/apache2/' for error log of vhost defined at /etc/apache2/sites-enabled/000-default.conf:1
AH00014: Configuration check failed
Action 'configtest' failed.
The Apache error log may have more information.

Thanks

**Comment by olejon** [comment]
That directory should be created when Apache is installed, which it is when installing SpotCommander. Maybe you have delete it by accident. You can reinstall Apache using these commands:

```
sudo apt-get clean
sudo apt-get install --reinstall apache2
```

Apache should start after installation. If you get the same error message, tell me.

**Comment by makovz** [comment]
OK.. your suggestion resolved my issue!
I think it was due to my fstab entries included for ssd optimization:
tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0
tmpfs /var/tmp tmpfs defaults,noatime,mode=1777 0 0
tmpfs /var/log tmpfs defaults,noatime,mode=0755 0 0 
tmpfs /var/log/apt tmpfs defaults,noatime 0 0
none /var/cache unionfs dirs=/tmp:/var/cache=ro 0 0

I commented them and reinstalled apache as you suggested. Now spotcommander it's working.

Probably including an additional line:
tmpfs /var/log/apache2 tmpfs defaults,noatime,mode=1777 0 0
could resolve the problem.
What do you think about?

Many thanks!!

**Comment by olejon** [comment]
Keeping /var/log in RAM (tmpfs) is a bad idea. Modern SSDs last years and years without problems without these optimizations. Most such guides are outdated, only for the first generations of SSDs. I only keep /tmp as tmpfs since it is cleaned at reboot anyway.

**Comment by makovz** [comment]
ok, good to know it! I'll follow your suggestion.

Many thanks for your valuable support!
Spotcommander is great!!

Best

**Comment by olejon** [comment]
You're welcome. Thanks!
